### ISSUE TITLE
Bad URL when clicking on Apply and Close after clustering

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#111]
```
What steps will reproduce the problem?
1. Open a big datafile(>60k rows)
2. Cluster (in my case, these are addresses)
3. After a while (1-2 minutes), I get something like 6000 clusters.
4. It looks good, I click on Select All, then Apply and Close.
5. I get an error and a stack trace:
 javax.servlet.ServletException: Can't find project: missing or bad URL parameter
    at com.metaweb.gridworks.commands.Command.getProject(Command.java:108)
    at com.metaweb.gridworks.commands.EngineDependentCommand.doPost(EngineDependentCommand.java:43)
    at com.metaweb.gridworks.GridworksServlet.doPost(GridworksServlet.java:1

BUT BUT BUT:
When I select a small number of clusters(ex: 10) or when I filter before 
applying the clustering command, it works("Select all" then "Apply and Close" 
on 3000 clusters). My guess is that the URL returned by the web interface is 
too long and get truncated.

What is the expected output? What do you see instead?
The expected output should be the new clusters. I get an error and gridworks 
doesn't seems as stable as before the error.

What version of the product are you using? On what operating system?
Version 1.1-r878
I've tried on Windows 7 and Ubuntu 9.10.

```

Original issue reported on code.google.com by `olivier....@gmail.com` on 22 Jul 2010 at 3:36

**Comment by GoogleCodeExporter** [comment]
```
Hmm, this is really weird: the request sent when you click "apply and close" is 
a POST request (precisely for this reason) and it should never get truncated... 
and even if it was the case, the project parameter is sent URLencoded (and not 
in the POST payload).

Unfortunately, I'm unable to repro... can you give me your data to try it out?
```

Original comment by `stefa...@google.com` on 31 Aug 2010 at 6:19
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I'll send you a data file by the end of the week at your email address.

The data is not very confidential but it's licensed from a big scary company so 
I won't attach it to this comment.

Btw, we use firefox.
```

Original comment by `olivier....@gmail.com` on 1 Sep 2010 at 12:39

**Comment by GoogleCodeExporter** [comment]
```
Thanks, that works.
```

Original comment by `stefa...@google.com` on 1 Sep 2010 at 1:05

**Comment by GoogleCodeExporter** [comment]
```
Olivier, did you send me the file? I haven't received it yet.
```

Original comment by `stefa...@google.com` on 16 Sep 2010 at 9:43

**Comment by GoogleCodeExporter** [comment]
```
I'm closing this since I can't repro
```

Original comment by `stefa...@google.com` on 28 Sep 2010 at 7:23
- Changed state: **Invalid**
