### ISSUE TITLE
Error 500 Failed to initialize module rdf-exporter-extension

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#118]
```
What steps will reproduce the problem?
1. Checkout source
2. Follow GetDevelopmentVersion
3. Run gridworks

What is the expected output? What do you see instead?

HTTP ERROR 500

Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-exporter-extension 
[edu.mit.simile.butterfly.ButterflyModuleImpl]
    at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:458)
    at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:431)
    at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:297)
    at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
    at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
    at com.google.gridworks.GridworksServer.configure(Gridworks.java:243)
    at com.google.gridworks.GridworksServer.init(Gridworks.java:166)
    at com.google.gridworks.Gridworks.init(Gridworks.java:83)
    at com.google.gridworks.Gridworks.main(Gridworks.java:77)
Caused by: org.mozilla.javascript.EvaluatorException: Java class 
"com.google.gridworks.operations.OperationRegistry" has no public instance 
field or method named "registerOperation". 
(file:/C:/Users/tguidry/Downloads/Freebase/gridworks/main/webapp/../../extension
s/rdf-exporter/module/MOD-INF/controller.js#18)
    at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:109)
    at org.mozilla.javascript.Context.reportRuntimeError(Context.java:938)
    at org.mozilla.javascript.Context.reportRuntimeError(Context.java:994)
    at org.mozilla.javascript.Context.reportRuntimeError2(Context.java:964)
    at org.mozilla.javascript.JavaMembers.reportMemberNotFound(JavaMembers.java:870)
    at org.mozilla.javascript.NativeJavaClass.get(NativeJavaClass.java:135)
    at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:1617)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2227)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2214)
    at org.mozilla.javascript.gen.c8._c1(file:/C:/Users/tguidry/Downloads/Freebase/gridworks/main/webapp/../../extensions/rdf-exporter/module/MOD-INF/controller.js:18)
    at org.mozilla.javascript.gen.c8.call(file:/C:/Users/tguidry/Downloads/Freebase/gridworks/main/webapp/../../extensions/rdf-exporter/module/MOD-INF/controller.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
    at org.mozilla.javascript.gen.c8.call(file:/C:/Users/tguidry/Downloads/Freebase/gridworks/main/webapp/../../extensions/rdf-exporter/module/MOD-INF/controller.js)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
    at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:456)
    ... 8 more


```

Original issue reported on code.google.com by `thadguidry` on 24 Aug 2010 at 3:57
- Blocked on: #1221

**Comment by GoogleCodeExporter** [comment]
```
GOOFED.  My build was pointed to another folder accidentally.  Please update to 
NOFIX.
```

Original comment by `thadguidry` on 24 Aug 2010 at 5:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `stefa...@google.com` on 24 Aug 2010 at 5:57
- Changed state: **Invalid**
