### ISSUE TITLE
Exporting to Excel on attached project raises server exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#122]
```
What steps will reproduce the problem?

1. Import the attached project.  (I tried to create a smaller TSV file that 
exhibits the problem but I couldn't.)
2. Attempt to export filtered records (all of them, by default) to Excel.
3. The operation fails; the following web page is generated:

What is the expected output? What do you see instead?

Instead of generating an Excel file, a web page with the following is generated:

HTTP ERROR 500

Problem accessing /command/core/export-rows/test3.xls. Reason:

    STREAM

Caused by:

java.lang.IllegalStateException: STREAM
    at org.mortbay.jetty.Response.getWriter(Response.java:616)
    at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.getWriter(GzipFilter.java:358)
    at com.google.gridworks.commands.Command.respond(Command.java:194)
    at com.google.gridworks.commands.Command.respondException(Command.java:262)
    at com.google.gridworks.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:59)
    at com.google.gridworks.GridworksServlet.service(GridworksServlet.java:120)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Powered by Jetty://


What version of the product are you using? On what operating system?

Trunk, Windows 7

Please provide any additional information below.

The exception does not occur if you export to CSV or TSV (but there is another 
problem, which I'll report separately).

```

Original issue reported on code.google.com by `bil...@gmail.com` on 2 Sep 2010 at 7:08

Attachments:
- [facebook-musician-pages.gridworks.tar.gz](https://storage.googleapis.com/google-code-attachments/google-refine/issue-122/comment-0/facebook-musician-pages.gridworks.tar.gz)

**Comment by GoogleCodeExporter** [comment]
```
Fixed by r1370
```

Original comment by `dfhu...@google.com` on 28 Sep 2010 at 3:45
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `tfmorris` on 18 Sep 2012 at 2:58
- Added labels: **Milestone-2.0**
