### ISSUE TITLE
Reconciling fails due to "unknown error"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#124]
```
What steps will reproduce the problem?
1.Reconcile ->Start Reconciling
2.Select Musical Artist (music/artist)
3. Use relevance service 
4. Start Reconciling

What is the expected output? What do you see instead?
I would expect to see the reconciling complete and display the results. I am 
seeing it quit before completing the task with the an indicator saying "unknown 
error". 

What version of the product are you using? On what operating system?
Gridworks 1.1 on Mac OS 6.x in Safari browser

Please provide any additional information below.
I have tried running the reconcile several times. Each time it quits at a 
different percentage of completion. 

Is there a log file anywhere or a way to track down this "unknown error" and 
what could be causing it?

```

Original issue reported on code.google.com by `nsincag...@nuemeta.com` on 5 Sep 2010 at 3:51

**Comment by GoogleCodeExporter** [comment]
```
I was able to get more information on this "Unknown error". When I run 
Gridworks on Windows XP there is a command window that displays the error. Here 
is the error message displayed in the command line window:

java.io.IOException: Server returned HTTP response code: 503 for URL: http://api
.freebase.com/api/service/search?indent=1&queries=%7B%22q0%3Asearch%22%3A%7B%22q
uery%22%3A%22ALBUQUERQUE+++++++++++++++++++++++++++++%22%2C%22limit%22%3A3%2C%22
type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_strict%22%3A%22should%22%2C%22type_ex
clude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffreebase%22%2C
%22stemmed%22%3A1%7D%2C%22q1%3Asearch%22%3A%7B%22query%22%3A%22LIVE+AT+PIEDMONT+
PAR++++++++++++++++++++%22%2C%22limit%22%3A3%2C%22type%22%3A%22%2Fmusic%2Falbum%
22%2C%22type_strict%22%3A%22should%22%2C%22type_exclude%22%3A%22%2Fcommon%2Fimag
e%22%2C%22domain_exclude%22%3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%7D%2C%22q2%3
Asearch%22%3A%7B%22query%22%3A%2215+PEGADITAS+DEL+MARIACHI+VARGAS++++++++%22%2C%
22limit%22%3A3%2C%22type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_strict%22%3A%22sh
ould%22%2C%22type_exclude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain_exclude%22%3A
%22%2Ffreebase%22%2C%22stemmed%22%3A1%7D%2C%22q3%3Asearch%22%3A%7B%22query%22%3A
%22YO+SOY+EL+SON+CUBANO++++++++++++++++++++%22%2C%22limit%22%3A3%2C%22type%22%3A
%22%2Fmusic%2Falbum%22%2C%22type_strict%22%3A%22should%22%2C%22type_exclude%22%3
A%22%2Fcommon%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffreebase%22%2C%22stemmed
%22%3A1%7D%2C%22q4%3Asearch%22%3A%7B%22query%22%3A%2220+%2F+4+MERENGUE+VOL.+2+++
+++++++++++++++%22%2C%22limit%22%3A3%2C%22type%22%3A%22%2Fmusic%2Falbum%22%2C%22
type_strict%22%3A%22should%22%2C%22type_exclude%22%3A%22%2Fcommon%2Fimage%22%2C%
22domain_exclude%22%3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%7D%2C%22q5%3Asearch%
22%3A%7B%22query%22%3A%22Jazz+In+Film++++++++++++++++++++++++++++%22%2C%22limit%
22%3A3%2C%22type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_strict%22%3A%22should%22%
2C%22type_exclude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffr
eebase%22%2C%22stemmed%22%3A1%7D%2C%22q6%3Asearch%22%3A%7B%22query%22%3A%2240+BA
CHATAS+PODEROSA++++++++++++++++++++%22%2C%22limit%22%3A3%2C%22type%22%3A%22%2Fmu
sic%2Falbum%22%2C%22type_strict%22%3A%22should%22%2C%22type_exclude%22%3A%22%2Fc
ommon%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%
7D%2C%22q7%3Asearch%22%3A%7B%22query%22%3A%22LIVE+IN+EUROPE%28EDITE+++++++++++++
+++++++%22%2C%22limit%22%3A3%2C%22type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_str
ict%22%3A%22should%22%2C%22type_exclude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain
_exclude%22%3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%7D%2C%22q8%3Asearch%22%3A%7B
%22query%22%3A%22THE+BOY+IS+MINE+++++++++++++++++++++++++%22%2C%22limit%22%3A3%2
C%22type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_strict%22%3A%22should%22%2C%22typ
e_exclude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffreebase%2
2%2C%22stemmed%22%3A1%7D%2C%22q9%3Asearch%22%3A%7B%22query%22%3A%22DAMN+RIGHT%2C
+I%27VE+GOT+THE+BLUES++++++++++%22%2C%22limit%22%3A3%2C%22type%22%3A%22%2Fmusic%
2Falbum%22%2C%22type_strict%22%3A%22should%22%2C%22type_exclude%22%3A%22%2Fcommo
n%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%7D%7
D
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown So
urce)
        at com.metaweb.gridworks.model.recon.HeuristicReconConfig.batchReconUsin
gRelevance(HeuristicReconConfig.java:238)
        at com.metaweb.gridworks.model.recon.HeuristicReconConfig.batchRecon(Heu
risticReconConfig.java:198)
        at com.metaweb.gridworks.operations.recon.ReconOperation$ReconProcess.ru
n(ReconOperation.java:243)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-15" java.lang.IndexOutOfBoundsException: Index: 0, S
ize: 0
        at java.util.ArrayList.RangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.metaweb.gridworks.operations.recon.ReconOperation$ReconProcess.ru
n(ReconOperation.java:245)
        at java.lang.Thread.run(Unknown Source)


```

Original comment by `nsincag...@gmail.com` on 6 Sep 2010 at 5:37

**Comment by GoogleCodeExporter** [comment]
```
Are you still getting the error?  When I try that query interactively now, it 
returns successfully.  Perhaps you hit a transient error on the server?  (It 
still should provide better error reporting though, so you don't have to resort 
to looking at the console)
```

Original comment by `tfmorris` on 6 Sep 2010 at 6:31

**Comment by GoogleCodeExporter** [comment]
```
Yes, I am still getting the "Unknown error" message when my reconcile process 
quits. However, I am not always seeing the errors dump to the console window. 
The last two times I tried to reconcile against Freebase, no error information 
was displayed in the console. Maybe the errors in the console are unrelated to 
the "Unknown error" warning I get in the lefthand side of my browser.

Is there any thing I can do to help track down this issue?  
```

Original comment by `nsincag...@gmail.com` on 6 Sep 2010 at 7:54

**Comment by GoogleCodeExporter** [comment]
```
Actually I'm seeing timeouts in the web client for simple things like the 
autocomplete dialog (which also uses the reconciliation/search services), so it 
could be a general site issue.  It's possible someone's hammering the server 
hard creating a high load or that there's a server issue, but in either case 
it's unlikely to get looked at until people are back from holiday tomorrow.
```

Original comment by `tfmorris` on 6 Sep 2010 at 8:20

**Comment by GoogleCodeExporter** [comment]
```
My reconcile quit and I this error was in the console window. It seems like 
this time it was correlated to the failure. 

java.io.IOException: Server returned HTTP response code: 503 for URL: 
http://api.freebase.com/api/service/search?indent=1&queries=%7B%22q0%3Asearch%22
%3A%7B%22query%22%3A%22LOOSE+MY+BREATH+++++++++++++++++++++++++%22%2C%22limit%22
%3A3%2C%22type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_strict%22%3A%22should%22%2C
%22type_exclude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffree
base%22%2C%22stemmed%22%3A1%7D%2C%22q1%3Asearch%22%3A%7B%22query%22%3A%22STARDUS
T+%2830TH+ANNIVERSARY+LEGACY+EDITIO%22%2C%22limit%22%3A3%2C%22type%22%3A%22%2Fmu
sic%2Falbum%22%2C%22type_strict%22%3A%22should%22%2C%22type_exclude%22%3A%22%2Fc
ommon%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%
7D%2C%22q2%3Asearch%22%3A%7B%22query%22%3A%22Fiesta+Songs%21++++++++++++++++++++
+++++++%22%2C%22limit%22%3A3%2C%22type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_str
ict%22%3A%22should%22%2C%22type_exclude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain
_exclude%22%3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%7D%2C%22q3%3Asearch%22%3A%7B
%22query%22%3A%22I+DO%21+I+DO%21+++++++++++++++++++++++++++++%22%2C%22limit%22%3
A3%2C%22type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_strict%22%3A%22should%22%2C%2
2type_exclude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffreeba
se%22%2C%22stemmed%22%3A1%7D%2C%22q4%3Asearch%22%3A%7B%22query%22%3A%22You+In+Fl
ames+++++++++++++++++++++++++++%22%2C%22limit%22%3A3%2C%22type%22%3A%22%2Fmusic%
2Falbum%22%2C%22type_strict%22%3A%22should%22%2C%22type_exclude%22%3A%22%2Fcommo
n%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%7D%2
C%22q5%3Asearch%22%3A%7B%22query%22%3A%22Brahms+++++++++++++++++++++++++++++++++
+%22%2C%22limit%22%3A3%2C%22type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_strict%22
%3A%22should%22%2C%22type_exclude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain_exclu
de%22%3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%7D%2C%22q6%3Asearch%22%3A%7B%22que
ry%22%3A%22MUSIC+FROM+%26+INSPIRED+BY+THE+MOTION+PICT%22%2C%22limit%22%3A3%2C%22
type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_strict%22%3A%22should%22%2C%22type_ex
clude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffreebase%22%2C
%22stemmed%22%3A1%7D%2C%22q7%3Asearch%22%3A%7B%22query%22%3A%22ALL+THAT+IS+WITHI
N+ME+++++++++++++++++++%22%2C%22limit%22%3A3%2C%22type%22%3A%22%2Fmusic%2Falbum%
22%2C%22type_strict%22%3A%22should%22%2C%22type_exclude%22%3A%22%2Fcommon%2Fimag
e%22%2C%22domain_exclude%22%3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%7D%2C%22q8%3
Asearch%22%3A%7B%22query%22%3A%22HOURGLASS+-+VOLUME+II+-+THE+EPIC+YEARS+%28%22%2
C%22limit%22%3A3%2C%22type%22%3A%22%2Fmusic%2Falbum%22%2C%22type_strict%22%3A%22
should%22%2C%22type_exclude%22%3A%22%2Fcommon%2Fimage%22%2C%22domain_exclude%22%
3A%22%2Ffreebase%22%2C%22stemmed%22%3A1%7D%2C%22q9%3Asearch%22%3A%7B%22query%22%
3A%22Sometimes+I+Dream%3A+Live+In+Concert++++++%22%2C%22limit%22%3A3%2C%22type%2
2%3A%22%2Fmusic%2Falbum%22%2C%22type_strict%22%3A%22should%22%2C%22type_exclude%
22%3A%22%2Fcommon%2Fimage%22%2C%22domain_exclude%22%3A%22%2Ffreebase%22%2C%22ste
mmed%22%3A1%7D%7D                                                               
                  at 
sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)      
                                                                             at 
com.metaweb.gridworks.model.recon.HeuristicReconConfig.batchReconUsingRelevance(
HeuristicReconConfig.java:238)                                               at 
com.metaweb.gridworks.model.recon.HeuristicReconConfig.batchRecon(HeuristicRecon
Config.java:198)                                                             at 
com.metaweb.gridworks.operations.recon.ReconOperation$ReconProcess.run(ReconOper
ation.java:243)                                                              at 
java.lang.Thread.run(Unknown Source)                                 Exception 
in thread "Thread-16" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0    

at java.util.ArrayList.RangeCheck(Unknown Source)                               
at java.util.ArrayList.get(Unknown Source)                                      
at 
com.metaweb.gridworks.operations.recon.ReconOperation$ReconProcess.run(ReconOper
ation.java:245)                                                              at 
java.lang.Thread.run(Unknown Source)

```

Original comment by `nsincag...@gmail.com` on 6 Sep 2010 at 9:13

**Comment by GoogleCodeExporter** [comment]
```
I think this was an issue with the Freebase Relevance service, let's reopen if 
it shows up again
```

Original comment by `stefa...@google.com` on 28 Sep 2010 at 7:30
- Changed state: **Invalid**
