### ISSUE TITLE
Add column from Freebase raises exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#127]
```
What steps will reproduce the problem?
1. Import the attached project (two rows, two columns)
2. Click on the "Freebase ID" menu and select "Edit Column" > "Add Columns From 
Freebase...
3. Specify the new column as /imdb/topic/title_id and press OK

What is the expected output? What do you see instead?

In the UI, the status monitor indicates 100% completion but never actually 
completes.  It can be cancelled.

On the server console window, the following appears:

java.lang.NullPointerException at 
com.google.gridworks.model.changes.DataExtensionChange.save(DataExtensionChange.
java:264)
        at com.google.gridworks.history.History.writeOneChange(History.java:74)
        at com.google.gridworks.history.History.writeOneChange(History.java:67)
        at com.google.gridworks.history.History.writeOneChange(History.java:56)
        at com.google.gridworks.io.FileHistoryEntryManager.saveChange(FileHistoryEntryManager.java:81)
        at com.google.gridworks.io.FileHistoryEntryManager.saveChange(FileHistoryEntryManager.java:70)
        at com.google.gridworks.history.HistoryEntry.apply(HistoryEntry.java:100)
        at com.google.gridworks.history.History.addEntry(History.java:98)
        at com.google.gridworks.operations.column.ExtendDataOperation$ExtendDataProcess.run(ExtendDataOperation.java:270)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-39" java.lang.RuntimeException: Failed to apply 
change
        at com.google.gridworks.history.HistoryEntry.apply(HistoryEntry.java:106)
        at com.google.gridworks.history.History.addEntry(History.java:98)
        at com.google.gridworks.operations.column.ExtendDataOperation$ExtendDataProcess.run(ExtendDataOperation.java:270)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.google.gridworks.model.changes.DataExtensionChange.save(DataExtensionChange.java:264)
        at com.google.gridworks.history.History.writeOneChange(History.java:74)
        at com.google.gridworks.history.History.writeOneChange(History.java:67)
        at com.google.gridworks.history.History.writeOneChange(History.java:56)
        at com.google.gridworks.io.FileHistoryEntryManager.saveChange(FileHistoryEntryManager.java:81)
        at com.google.gridworks.io.FileHistoryEntryManager.saveChange(FileHistoryEntryManager.java:70)
        at com.google.gridworks.history.HistoryEntry.apply(HistoryEntry.java:100
)
        ... 3 more

What version of the product are you using? On what operating system?

Trunk, Windows 7 

Please provide any additional information below.

Although it's presumably unusual to have two keys in the /en namespace that map 
to the same topic, I don't think that's what's causing it.  There are other 
cases where this exception occurs; this was just the simplest one I could 
identify.

I have no idea what's causing this or what a workaround might be.

```

Original issue reported on code.google.com by `bil...@gmail.com` on 10 Sep 2010 at 1:45

Attachments:
- [test.gridworks.tar.gz](https://storage.googleapis.com/google-code-attachments/google-refine/issue-127/comment-0/test.gridworks.tar.gz)

**Comment by GoogleCodeExporter** [comment]
```
Fixed by r1261.
```

Original comment by `dfhu...@google.com` on 10 Sep 2010 at 5:05
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `tfmorris` on 18 Sep 2012 at 2:58
- Added labels: **Milestone-2.0**
