### ISSUE TITLE
Import .zip archive fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#228]
```
What steps will reproduce the problem?
1. following instructions found here 
http://code.google.com/p/google-refine/wiki/Importers
2. select a .zip archive
(in this case, a directory of XML files generated by oai2rdf -dump    
(http://simile.mit.edu/wiki/OAI-PMH_RDFizer)
3. Create Project


What is the expected output? What do you see instead?

    see attached screenshot.  

What version of the product are you using? On what operating system?

version 2.0 
OSX 10.6.4
FF 3.6.12

Please provide any additional information below.

```

Original issue reported on code.google.com by `musebrar...@gmail.com` on 17 Nov 2010 at 5:13
- Blocking: #131

Attachments:
- [101116-0001.png](https://storage.googleapis.com/google-code-attachments/google-refine/issue-228/comment-0/101116-0001.png)

**Comment by GoogleCodeExporter** [comment]
```
Also fails with similar error on tar.gz archive.
```

Original comment by `musebrar...@gmail.com` on 17 Nov 2010 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the bug report.  I can reproduce this.

It's being caused by line 211 of com.google.RefineServlet.getTempDir calling a 
null variable, config.

It appears that com.google.RefineServlet.config, is only ever read or destroyed 
and doesn't seem to be assigned to.  I'd imagine it needs to be assigned to at 
some point in the com.google.RefineServlet.init method, but I'm not familiar 
enough with Servlets to be able to fix it at this moment.  Hopefully someone 
else can step in and fix it...(any dev want to take this task??)

```

Original comment by `iainsproat` on 17 Nov 2010 at 10:26
- Changed state: **Accepted**
- Added labels: **Component-Logic**, **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
I have run into exactly the same issue:

Running
Version 2.0
Windows XP
FF3.6.12
```

Original comment by `pjos...@gmail.com` on 17 Nov 2010 at 7:14

**Comment by GoogleCodeExporter** [comment]
```
I'll take a look.
```

Original comment by `dfhu...@google.com` on 20 Nov 2010 at 11:08

**Comment by GoogleCodeExporter** [comment]
```
I'm running Ubuntu x64 (10.10) and I get a very similar error on importing a 
tgz file:

java.lang.NullPointerException
    at com.google.refine.RefineServlet.getTempDir(RefineServlet.java:211)
    at com.google.refine.RefineServlet.getTempFile(RefineServlet.java:220)
    at com.google.refine.commands.project.CreateProjectCommand.save(CreateProjectCommand.java:345)
    at com.google.refine.commands.project.CreateProjectCommand.internalImportFile(CreateProjectCommand.java:216)
    at com.google.refine.commands.project.CreateProjectCommand.internalImport(CreateProjectCommand.java:169)
    at com.google.refine.commands.project.CreateProjectCommand.doPost(CreateProjectCommand.java:112)
    at com.google.refine.RefineServlet.service(RefineServlet.java:174)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:636)
```

Original comment by `jagt...@gmail.com` on 4 Dec 2010 at 9:41

**Comment by GoogleCodeExporter** [comment]
```
Getting the same thing on Centos 5.5, and Refine 2.0:

java.lang.NullPointerException
    at com.google.refine.RefineServlet.getTempDir(RefineServlet.java:211)
    at com.google.refine.RefineServlet.getTempFile(RefineServlet.java:220)
    at com.google.refine.commands.project.CreateProjectCommand.save(CreateProjectCommand.java:345)
    at com.google.refine.commands.project.CreateProjectCommand.internalImportFile(CreateProjectCommand.java:216)
    at com.google.refine.commands.project.CreateProjectCommand.internalImport(CreateProjectCommand.java:169)
    at com.google.refine.commands.project.CreateProjectCommand.doPost(CreateProjectCommand.java:112)
    at com.google.refine.RefineServlet.service(RefineServlet.java:174)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:636)
```

Original comment by `ehsanul...@gmail.com` on 29 Dec 2010 at 7:48

**Comment by GoogleCodeExporter** [comment]
```
I should add that, this issue occurs for me with .tar.gz files, zip files, 
.tar.bz2 files and I imagine any archive.
```

Original comment by `ehsanul...@gmail.com` on 29 Dec 2010 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
Ran into the same trouble trying to load the attached file (if that can be of 
any help)

Version of refine
google-refine-2.0-r1836.zip



java.lang.NullPointerException
    at com.google.refine.RefineServlet.getTempDir(RefineServlet.java:211)
    at com.google.refine.RefineServlet.getTempFile(RefineServlet.java:220)
    at com.google.refine.commands.project.CreateProjectCommand.save(CreateProjectCommand.java:345)
    at com.google.refine.commands.project.CreateProjectCommand.internalImportFile(CreateProjectCommand.java:216)
    at com.google.refine.commands.project.CreateProjectCommand.internalImport(CreateProjectCommand.java:169)
    at com.google.refine.commands.project.CreateProjectCommand.doPost(CreateProjectCommand.java:112)
    at com.google.refine.RefineServlet.service(RefineServlet.java:174)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

```

Original comment by `f8f...@gmail.com` on 9 Mar 2011 at 3:55

Attachments:
- [Bixi1h.zip](https://storage.googleapis.com/google-code-attachments/google-refine/issue-228/comment-8/Bixi1h.zip)

**Comment by GoogleCodeExporter** [comment]
```
I also ran into this problem while uploading zip archive to Google Refine 
version 2.0, using Chrome (v10.0.648.127 beta) on OSX (v10.6.6).  Appreciate 
your help in resolving it. 
```

Original comment by `sergio.b...@gmail.com` on 17 Mar 2011 at 2:16

**Comment by GoogleCodeExporter** [comment]
```
I was able to get the import to run successfully, but some of the data cells 
are corrupted. Instead of seeing the real data, I'm seeing what appears to be 
the filename (within the archive), with some sort of number. 

Running Chrome 11.0.696.68 and OSX 10.6.7.  Attached is my (simplified) data 
file
```

Original comment by `hamiltont` on 18 May 2011 at 5:01

Attachments:
- [data.tar](https://storage.googleapis.com/google-code-attachments/google-refine/issue-228/comment-10/data.tar)

**Comment by GoogleCodeExporter** [comment]
```
Oops - Just noticed that *.tar is not supported, only the zipped versions (BTW, 
why not? If I'm working locally, then what's the point of compressing something 
that's about to be decompressed anyways?)  

Anyway, I gzipped the archive and uploaded (the same data) in *.tar.gz format. 
This time, I got the exception that everyone else is seeing: 

java.lang.NullPointerException
    at com.google.refine.RefineServlet.getTempDir(RefineServlet.java:211)
    at com.google.refine.RefineServlet.getTempFile(RefineServlet.java:220)
    at com.google.refine.commands.project.CreateProjectCommand.save(CreateProjectCommand.java:345)
    at com.google.refine.commands.project.CreateProjectCommand.internalImportFile(CreateProjectCommand.java:216)
    at com.google.refine.commands.project.CreateProjectCommand.internalImport(CreateProjectCommand.java:169)
    at com.google.refine.commands.project.CreateProjectCommand.doPost(CreateProjectCommand.java:112)
    at com.google.refine.RefineServlet.service(RefineServlet.java:174)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)

File attached in case it's useful
```

Original comment by `hamiltont` on 18 May 2011 at 5:03

Attachments:
- [data.tar.gz](https://storage.googleapis.com/google-code-attachments/google-refine/issue-228/comment-11/data.tar.gz)

**Comment by GoogleCodeExporter** [comment]
```
I'm going to mark this as fixed, by r1918. We'll worry about importing several 
files inside a single archive file later, in the new importer framework.
```

Original comment by `dfhu...@gmail.com` on 6 Jun 2011 at 9:21
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Is there a new issue to track the "importing several files inside a single 
archive" feature?
```

Original comment by `iainsproat` on 7 Jun 2011 at 7:56

**Comment by GoogleCodeExporter** [comment]
```
Iain, no, but it's baked in in the new importer framework.
```

Original comment by `dfhu...@gmail.com` on 7 Jun 2011 at 5:32

**Comment by GoogleCodeExporter** [comment]
```
Thanks everyone!    If I understand the last comment correctly, the new 
importer framework will allow the use of multiple files without having to make 
an archive?  That's the real function I was looking for, although it still 
would be nice to allow "importing several files from inside a single archive" 
feature. 
```

Original comment by `musebrar...@gmail.com` on 7 Jun 2011 at 5:38

**Comment by GoogleCodeExporter** [comment]
Original comment by `tfmorris` on 9 Jun 2011 at 7:58
- Added labels: **Milestone-2.1**

**Comment by GoogleCodeExporter** [comment]
```
Yes, it should allow importing several files not inside an archive file, but 
you'd need to specify each file individually. You can't just provide a 
directory. This is because by operating through the web browser, Refine can't 
see the local file system directory and cannot list the files in a given 
directory.
```

Original comment by `dfhu...@gmail.com` on 14 Aug 2011 at 3:16
