### ISSUE TITLE
Internet Explorer (IE 8) has significant issues with Refine numeric facets and others features

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#269]
```
What steps will reproduce the problem?
1.Run Google-Refine from the EXE or BAT file
2.select Excel spreadsheet data with 26,000 rows
3. Tell it to only imporet the first 1000
4.  It will import all of them.
5. Tell it to do a numeric facet on one column.
6. It goes into forever waiting loop.

What is the expected output? What do you see instead?
I would have expected to import only 1000 rows and then I would expect to see 
the kind of distribution information on my numeric column that I saw in the 
demo.

What version of the product are you using? On what operating system?
I am using Version 2.0 [r1836] on Windows XP service pack 3 with Java release 6

Please provide any additional information below.

I previously has no success with any filters on the new project window, but I 
have had very good success with text facets on this very same dataset.  I am 
using Internet Explorer 8 as my browser
```

Original issue reported on code.google.com by `DanielJo...@gmail.com` on 30 Nov 2010 at 8:26

**Comment by GoogleCodeExporter** [comment]
```
Could you please provide some sample data that's giving you trouble and that we 
can test on?
```

Original comment by `dfhu...@gmail.com` on 2 Dec 2010 at 7:13

**Comment by GoogleCodeExporter** [comment]
```
My original failed example was the full dataset with 26000 observataions.  I 
just tested it with a dataset having only 1001 observations and I am having the 
same problems, so I am sending the smaller dataset.
```

Original comment by `DanielJo...@gmail.com` on 3 Dec 2010 at 4:37

Attachments:
- [htdbh1000.xlsx](https://storage.googleapis.com/google-code-attachments/google-refine/issue-269/comment-2/htdbh1000.xlsx)

**Comment by GoogleCodeExporter** [comment]
```
I have been able to import your xlsx file, and to create numeric facets on 
"weight" and "totht". Do you have access to Firefox or Chrome? I'm suspecting 
that you might be seeing an IE-specific issue.

(We coded Google Refine using standard web technologies, through the jQuery 
library. This works quite well for Firefox, Chrome, and Safari. We don't try to 
compensate for browser-specific non-standard behaviors.)

```

Original comment by `dfhu...@gmail.com` on 5 Dec 2010 at 1:55

**Comment by GoogleCodeExporter** [comment]
```
The computer that I was hoping to use is limited to IE by company policy.  In 
order to see if this is the problem I installed  Refine on my home computer.  
It gives me errors that I haven't been able to figure out:

HTTP ERROR 500

Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to wire modules
    at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:435)
    at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
    at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
    at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
    at com.google.refine.RefineServer.configure(Refine.java:278)
    at com.google.refine.RefineServer.init(Refine.java:200)
    at com.google.refine.Refine.init(Refine.java:117)
    at com.google.refine.Refine.main(Refine.java:111)
Caused by: java.lang.RuntimeException: Cannot wire module 'freebase' because no 
module implements the required interface 'core'
    at edu.mit.simile.butterfly.Butterfly.wireModules(Butterfly.java:802)
    at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:433)

```

Original comment by `DanielJo...@gmail.com` on 7 Dec 2010 at 4:45

**Comment by GoogleCodeExporter** [comment]
```
Would you mind trying to check out the development version and see if that 
error is still there?

http://code.google.com/p/google-refine/wiki/GetDevelopmentVersion
```

Original comment by `dfhu...@gmail.com` on 7 Dec 2010 at 6:30

**Comment by GoogleCodeExporter** [comment]
```
I considered doing so, but it looks pretty involved.  I'd install another 
program, but this looks like much more than that and the end result, though 
nice, might not be worth the time investment.
```

Original comment by `DanielJo...@gmail.com` on 8 Dec 2010 at 3:05

**Comment by GoogleCodeExporter** [comment]
```
I see the exact same problem in IE 8 on XP with the automobile data set from 
the UCI Machine Learning repository. I can create a text facet from the "make" 
column, but Google Refine hangs with "Working" when trying to create a numeric 
facet from "bore" or "price". Could this be because some of the data in these 
columns are missing (with "?" instead of a numeric value)? A data cleaning app 
should be able to handle bogus values in a numeric column!

See here for the data: http://archive.ics.uci.edu/ml/datasets/Automobile

Raw data without column names are here: 
http://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data

```

Original comment by `danapoke...@yahoo.com` on 22 Dec 2010 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
To quote one of our developers in this issue above:
(We coded Google Refine using standard web technologies, through the jQuery 
library. This works quite well for Firefox, Chrome, and Safari. We don't try to 
compensate for browser-specific non-standard behaviors.)

I tried the autos/imports-85.data and it works flawlessly in Google Chrome, and 
Firefox, but your right, the numeric facet hangs in IE8.
```

Original comment by `thadguidry` on 22 Dec 2010 at 5:36

**Comment by GoogleCodeExporter** [comment]
```
I should also add that I choose to auto-detect the value types, but you can 
also uncheck that option prior to loading, and once loaded, then use Edit Cells 
-> Common Transforms -> To Number
```

Original comment by `thadguidry` on 22 Dec 2010 at 5:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `tfmorris` on 22 Dec 2010 at 6:05
- Changed title: **Internet Explorer (IE 8) has significant issues with Refine numeric facets and others features**

**Comment by GoogleCodeExporter** [comment]
```
Internet Explorer support was improved in Refine 2.5.  Can you retest and let 
us know if this issue still exists?
```

Original comment by `tfmorris` on 18 Sep 2012 at 7:50
