### ISSUE TITLE
Problems running on Mac Leopard

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#345]
```

What steps will reproduce the problem?

1. I installed Refine into the Applications folder.
2. I double click on the icon in Applications, the blue diamond appears in my 
icon bar at the bottom of the screen, it bounces, stops bouncing.
3. Nothing more happens
4. I tried to quit everything, same problem.
5. I tried to reboot, same problem.

What is the expected output? What do you see instead?

Expected - Refine loads and runs in a browser. See - blue diamond bounces, 
nothing more happens.

What version of Google Refine are you using?

Refine 2.0

What operating system and browser are you using?

Mac Leopard 10.5.8 2 GHz Intel Core 2 Duo Processor

Is this problem specific to the type of browser you're using or it happens

No. I tried in Firefox and Safari.

in all the browsers you tried?

Please provide any additional information below.

I've used this program on many other Macs and PCs, and it has always worked. 
So, I don't think I'M the problem here.

Thanks!

```

Original issue reported on code.google.com by `bencolme...@gmail.com` on 8 Mar 2011 at 8:23

**Comment by GoogleCodeExporter** [comment]
```
When the icon stops bouncing, could you open your browser and enter

127.0.0.1:3333

I'm not sure why that doesn't happen automatically.
```

Original comment by `dfhu...@gmail.com` on 8 Mar 2011 at 9:53

**Comment by GoogleCodeExporter** [comment]
```
Hey,

I have 10.5.8 too. In my case, the icon appears in the task bar for a moment & 
then disappears. I think problem is the lack of Java 1.6 on Leopard x-(  

Here is the stack trace i get on running it via the command line:

localhost:MacOS username$ ./JavaApplicationStub 
[JavaAppLauncher] Requested [1.6+], launching in [1.5] instead.
[JavaAppLauncher Error] CallStaticVoidMethod() threw an exception
Exception in thread "main" java.lang.UnsupportedClassVersionError: Bad version 
number in .class file
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:676)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:317)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:280)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:375)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:242)
    at apple.launcher.LaunchRunner.loadMainMethod(LaunchRunner.java:55)
    at apple.launcher.LaunchRunner.run(LaunchRunner.java:111)
    at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:50)
    at apple.launcher.JavaApplicationLauncher.launch(JavaApplicationLauncher.java:52)


Any ideas?

I have been able to run it without any issues on Linux.

Thanks,

..m
```

Original comment by `m.mara...@gmail.com` on 2 Jul 2011 at 12:38

**Comment by GoogleCodeExporter** [comment]
```
Do you have a Core 2 Duo based machine? If so you should be able to run Java 6. 
If it's an older core duo machine you may be stuck. 
http://stackoverflow.com/questions/331777/what-are-my-options-for-running-java-6
-on-os-x

```

Original comment by `tfmorris` on 2 Jul 2011 at 2:58

**Comment by GoogleCodeExporter** [comment]
```
Ah i see :)  Thanks for the link, will try it out. I have a Core 2 Duo, but 
I've been relying on Apple's Java all this time...  Will try it out :)
```

Original comment by `m.mara...@gmail.com` on 3 Jul 2011 at 3:18

**Comment by GoogleCodeExporter** [comment]
Original comment by `tfmorris` on 8 Oct 2011 at 7:21
- Changed state: **Invalid**
