### ISSUE TITLE
Transform involving NaN causes crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#378]
```
What steps will reproduce the problem?
1. Find a cell with numeric 0
2. Edit cells -> Transform: 
3.

What is the expected output? What do you see instead?

Expect to see NaN. Refine crashes ("Working")

What version of Google Refine are you using?

2.0

What operating system and browser are you using?

Windows Chrome



Please provide any additional information below.

18:49:10.140 [                   refine] GET /command/core/get-history (43ms)
18:49:10.146 [                   refine] POST /command/core/get-rows (6ms)
18:49:10.146 [                  command] Exception caught (0ms)
org.json.JSONException: Misplaced endArray.
        at org.json.JSONWriter.end(JSONWriter.java:167)
        at org.json.JSONWriter.endArray(JSONWriter.java:187)
        at com.google.refine.commands.row.GetRowsCommand.internalRespond(GetRows
Command.java:131)
        at com.google.refine.commands.row.GetRowsCommand.doPost(GetRowsCommand.j
ava:68)
        at com.google.refine.RefineServlet.service(RefineServlet.java:174)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511
)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)

        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:3
88)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:1
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:7
65)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)

        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:54
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnectio
n.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.
java:228)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source
)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Original issue reported on code.google.com by `paulm%pa...@gtempaccount.com` on 10 May 2011 at 5:51

**Comment by GoogleCodeExporter** [comment]
```
Sorry, the transform there should've been "value / value"
```

Original comment by `paulm%pa...@gtempaccount.com` on 10 May 2011 at 5:54

**Comment by GoogleCodeExporter** [comment]
```
Hi Paul, I can't reproduce this in trunk/. Could you check?
```

Original comment by `dfhu...@gmail.com` on 19 Sep 2011 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
This still exists in 2.5 RC2.  I'll take a look.
```

Original comment by `tfmorris` on 29 Nov 2011 at 7:25
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r2391.
```

Original comment by `tfmorris` on 29 Nov 2011 at 7:58
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dfhu...@google.com` on 11 Dec 2011 at 10:34
- Added labels: **Milestone-2.5**
