### ISSUE TITLE
IllegalStateException: Committed when fetching favicon

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#416]
```
Got this weird error message on the console when starting up Refine today.  
Don't have time to investigate right now...

16:00:16.846 [                butterfly] GET /images/logo-googlerefine40.png 
[ain] (0ms)
16:00:16.877 [          org.mortbay.log] /favicon.ico (31ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrap
er.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipF
lter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFil
er.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:180)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:51
)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servle
Handler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81

        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servle
Handler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:
88)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.ja
a:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:
65)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418

        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:5
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpC
nnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector
java:228)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExe
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecuto
.java:908)
        at java.lang.Thread.run(Thread.java:619)
16:00:16.987 [                butterfly] GET /images/favicon.png [main] (110ms)
16:00:52.977 [                butterfly] GET / [main] (35990ms)
16:00:53.195 [                butterfly] GET /wirings.js [main] (218ms)
16:00:53.227 [                butterfly] GET /images/favicon.png [main] (32ms)
16:00:53.227 [                butterfly] GET /images/logo-googlerefine-40.png [
ain] (0ms)
16:00:57.598 [                butterfly] GET / [main] (4371ms)
16:00:57.661 [                butterfly] GET / [main] (63ms)
16:00:58.644 [                butterfly] GET /images/favicon.png [main] (983ms)

```

Original issue reported on code.google.com by `tfmorris` on 23 Jun 2011 at 8:40

**Comment by GoogleCodeExporter** [comment]
```
For me, this issue only seems to happen with Firefox.  I have not experienced 
it on Google Chrome. (attached)
```

Original comment by `thadguidry` on 19 Sep 2011 at 5:57

Attachments:
- [ThadDebug_r2238.txt](https://storage.googleapis.com/google-code-attachments/google-refine/issue-416/comment-1/ThadDebug_r2238.txt)

**Comment by GoogleCodeExporter** [comment]
```
Stefano reports that this is a random non-fatal event which can be cleared by 
reloading the page.  Lowering priority...
```

Original comment by `tfmorris` on 8 Oct 2011 at 6:02
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**
