### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#446]
```
*****
If you don't know how to do something in Google Refine, please ask on the
mailing list. Also use the mailing list for discussions and comments.

http://groups.google.com/group/google-refine/

Only file an issue here if you discover a bug or want to request a new
feature.

Thank you.
*****
I got a 'memory issue'

HTTP ERROR 500

Problem accessing /command/core/create-project-from-upload. Reason:

    Java heap space
Caused by:

java.lang.OutOfMemoryError: Java heap space
    at java.util.ArrayList.<init>(ArrayList.java:112)
    at com.google.refine.model.RecordModel.update(RecordModel.java:120)
    at com.google.refine.model.Project.update(Project.java:255)
    at com.google.refine.commands.project.CreateProjectCommand.doPost(CreateProjectCommand.java:134)
    at com.google.refine.RefineServlet.service(RefineServlet.java:171)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)

What steps will reproduce the problem?
1. Try to upload a 'small' (10s of rows) txt file
2. Had loaded several, much larger files in same session
3. After a point all new files caused a 'freeze' (address bar not progressing)

What is the expected output? What do you see instead?

What version of Google Refine are you using?

Changed to 2.1 today, never seen the issue before

What operating system and browser are you using?

Max OS 10.7.1  Using latest version of safari

Is this problem specific to the type of browser you're using or it happens
in all the browsers you tried?

Please provide any additional information below.

```

Original issue reported on code.google.com by `yout...@organizationview.co.uk` on 9 Sep 2011 at 4:18

**Comment by GoogleCodeExporter** [comment]
```
Is this problem reproduceable with your small file?  If so, can you attach it 
here for debug purposes?

Not that memory is shared across all projects and recently opened projects are 
cached in memory, so it is theoretically possible that your new small project 
pushed you over the edge.
```

Original comment by `tfmorris` on 13 Sep 2011 at 8:50

**Comment by GoogleCodeExporter** [comment]
```
Andrew, could you please provide more info? (We'll wait for a few more days and 
close this as "can't repro".) Thanks.
```

Original comment by `dfhu...@gmail.com` on 27 Sep 2011 at 8:30

**Comment by GoogleCodeExporter** [comment]
```
Closing due to lack of response from reporter.  Feel free to reopen if you can 
provide additional information.
```

Original comment by `tfmorris` on 21 Oct 2011 at 4:05
- Changed state: **CantRepro**
