### ISSUE TITLE
Localized Windows cause save problems for Gridworks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#5]
```
I have russian Windows 7 installation and all usernames are Russian.

When use Gridworks and run any action that should save something I see 
following error on console and nothing saved too. 

java.io.FileNotFoundException: C:\Users\????
\AppData\Local\Gridworks\2206489941407.project\history\1273396606971.change
.zip (Системе не удается найти указанный путь)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:179)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:131)
    at 
com.metaweb.gridworks.history.HistoryEntry.saveChange(HistoryEntry.java:177
)
    at 
com.metaweb.gridworks.history.HistoryEntry.saveChange(HistoryEntry.java:172
)
    at 
com.metaweb.gridworks.history.HistoryEntry.apply(HistoryEntry.java:90)
    at com.metaweb.gridworks.history.History.addEntry(History.java:89)
    at 
com.metaweb.gridworks.process.QuickHistoryEntryProcess.performImmediate(Qui
ckHistoryEntryProcess.java:38)
    at 
com.metaweb.gridworks.process.ProcessManager.queueProcess(ProcessManager.ja
va:37)
    at 
com.metaweb.gridworks.commands.Command.performProcessAndRespond(Command.jav
a:130)
    at 
com.metaweb.gridworks.commands.EngineDependentCommand.doPost(EngineDependen
tCommand.java:48)
    at 
com.metaweb.gridworks.GridworksServlet.doPost(GridworksServlet.java:223)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at 
org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at 
org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at 
org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at 
org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at 
org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at 
org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at 
org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at 
org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at 
org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java
:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at 
org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:2
28)
    at 
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.j
ava:886)
    at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:
908)
    at java.lang.Thread.run(Thread.java:619)


```

Original issue reported on code.google.com by `ibeg...@gmail.com` on 9 May 2010 at 9:08

**Comment by GoogleCodeExporter** [comment]
```
Hmm, this is going to be interesting to fix since we don't have access to 
versions of windows that don't use the 
ASCII characters... how comfortable are you with programming? Could we send 
patches to you to try?
```

Original comment by `stefano.mazzocchi@gmail.com` on 10 May 2010 at 4:23

**Comment by GoogleCodeExporter** [comment]
Original comment by `stefano.mazzocchi@gmail.com` on 10 May 2010 at 4:52
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I am comfortable with programming so if patches will be available I will try 
them.
```

Original comment by `ibeg...@gmail.com` on 10 May 2010 at 4:56

**Comment by GoogleCodeExporter** [comment]
```
From the looks of the error message, it's the non-ASCII username, not 
necessarily the 
localized Windows version that is the issue.  There's a good chance that you'll 
be 
able to reproduce it by creating a test user account containing non-ASCII 
characters 
on a standard English Windows distribution.
```

Original comment by `tfmorris` on 10 May 2010 at 4:57

**Comment by GoogleCodeExporter** [comment]
```
Ah, good point Tom. I'll try that.
```

Original comment by `stefano.mazzocchi@gmail.com` on 10 May 2010 at 5:35

**Comment by GoogleCodeExporter** [comment]
Original comment by `dfhu...@gmail.com` on 10 May 2010 at 5:43

**Comment by GoogleCodeExporter** [comment]
```
I'll get to this when I get home on my Vista box with East Asian language 
support.
```

Original comment by `dfhu...@gmail.com` on 10 May 2010 at 8:11
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r707. ibegtin, could you check out the source and verify? Thanks.
```

Original comment by `dfhu...@gmail.com` on 11 May 2010 at 4:18
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `tfmorris` on 18 Sep 2012 at 2:21
- Added labels: **Milestone-2.0**

**Comment by GoogleCodeExporter** [comment]
Original comment by `tfmorris` on 18 Sep 2012 at 2:49
- Added labels: **Milestone-1.0**
- Removed labels: **Milestone-2.0**
