### ISSUE TITLE
DBpedia renconciliation problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#509]
```
What steps will reproduce the problem?
1. Choose a coloumn and the 
2. Start reconciling against it 
3. Choose DBpedia endpiont created using the RDF extension following the 
guidelines on the website

What is the expected output? What do you see instead?
"Reconcile each cell to an entity of one of these types:" should suggest 
something and unfortunately is empty

What version of Google Refine are you using?
the last one

What operating system and browser are you using?
Windows 7, chrome,explorer,firefox,...

Is this problem specific to the type of browser you're using or it happens
in all the browsers you tried?
all browsers

Please provide any additional information below.
This is the generated exception which is throwed when I select DBpedia:


Failed to guess cell types for load
{"q0":{"query":"Afghanistan","limit":3},"q1":{"query":"Albania","limit":3},"q2":
{"query":"Algeria","limit":3},"q3":{"query":"American 
Samoa","limit":3},"q4":{"query":"Andorra","limit":3},"q5":{"query":"Angola","lim
it":3},"q6":{"query":"Antigua and Barbuda","limit":3},"q7":{"query":"Arab 
World","limit":3},"q8":{"query":"Argentina","limit":3},"q9":{"query":"Armenia","
limit":3}} (3ms)
java.io.IOException: Server returned HTTP response code: 500 for URL: 
http://127.0.0.1:3333/extension/rdf-extension/services/dbpedia
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at com.google.refine.commands.recon.GuessTypesOfColumnCommand.guessTypes(GuessTypesOfColumnCommand.java:188)
    at com.google.refine.commands.recon.GuessTypesOfColumnCommand.doPost(GuessTypesOfColumnCommand.java:93)
    at com.google.refine.RefineServlet.service(RefineServlet.java:177)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source) 


```

Original issue reported on code.google.com by `perrone...@gmail.com` on 19 Dec 2011 at 1:09

**Comment by GoogleCodeExporter** [comment]
```
The RDF extension is provided separately from Refine and is supported by a 
different team.  The page that you downloaded the software from 
(http://lab.linkeddata.deri.ie/2010/grefine-rdf-extension/) has a link to the 
issue tracker (http://github.com/fadmaa/grefine-rdf-extension/issues)

p.s. I'm sure they'd appreciate an actual version number (e.g. 2.5, 2.1, etc) 
instead of the ambiguous "last one"
```

Original comment by `tfmorris` on 19 Dec 2011 at 1:49
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Is Freebase extension supported by the same team? Because I have some problem 
also with Freebase!  Thanks
```

Original comment by `perrone...@gmail.com` on 19 Dec 2011 at 2:14
