### ISSUE TITLE
Freebase reconciliation problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#510]
```
What steps will reproduce the problem?
1. Choose a coloumn 
2. Start reconciling against it using Freebase service

What is the expected output? What do you see instead?
"Reconcile each cell to an entity of one of these types:" should suggest 
something and unfortunately is empty

What version of Google Refine are you using?
google-refine-2.5

What operating system and browser are you using?
Windows 7, chrome,explorer,firefox,...

Is this problem specific to the type of browser you're using or it happens
in all the browsers you tried?
all browsers

Please provide any additional information below.
This is the generated exception which is throwed when I select Freebase:

18:32:04.908 [                  command] Failed to guess cell types for load
{"q0":{"query":"Afghanistan","limit":3},"q1":{"query":"Albania","limit":3},"q2":
{"query":"Algeria","limit":3},"q3":{"query":"American 
Samoa","limit":3},"q4":{"query":"Andorra","limit":3},"q5":{"query":"Angola","lim
it":3},"q6":{"query":"Antigua and Barbuda","limit":3},"q7":{"query":"Arab 
World","limit":3},"q8":{"query":"Argentina","limit":3},"q9":{"query":"Armenia","
limit":3}} (13ms)
java.net.UnknownHostException: 
4.standard-reconcile.dfhuynh.user.dev.freebaseapps.com
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.<init>(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
    at com.google.refine.commands.recon.GuessTypesOfColumnCommand.guessTypes(GuessTypesOfColumnCommand.java:175)
    at com.google.refine.commands.recon.GuessTypesOfColumnCommand.doPost(GuessTypesOfColumnCommand.java:93)
    at com.google.refine.RefineServlet.service(RefineServlet.java:177)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Thanks in advance
```

Original issue reported on code.google.com by `perrone...@gmail.com` on 19 Dec 2011 at 5:36

**Comment by GoogleCodeExporter** [comment]
```
It looks like perhaps your network is configured incorrectly.  When you paste 
the address 4.standard-reconcile.dfhuynh.user.dev.freebaseapps.com in your 
browser's address bar, does it bring up a page titled "Reconciliation Service 
API Test Dashboard"?

Does your network have a proxy or firewall which needs to be configured to 
allow Refine to access the external network?
```

Original comment by `tfmorris` on 19 Dec 2011 at 5:54

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your support!

As regards the first question I tried to open the mentioned service and is 
possible to do it both in Explorer and in Chrome.

I also checked the proxy settings and actually I'm using a proxy server for my 
LAN..what do you mean with configuring the proxy to allow Refine to access 
external network?
```

Original comment by `perrone...@gmail.com` on 20 Dec 2011 at 8:07

**Comment by GoogleCodeExporter** [comment]
```
I have some news...I changed the proxy settings and now at least Freebase works 
fine but I have some problems with the RDF extension yet trying to use DBpedia 
so I have opened an issue in the proper place asking for a solution to the 
problem.

Thanks
```

Original comment by `perrone...@gmail.com` on 20 Dec 2011 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
Glad to hear you got things fixed.  Thanks for lettings us know.  

```

Original comment by `tfmorris` on 20 Dec 2011 at 3:39
- Changed state: **Invalid**
