### ISSUE TITLE
ConcurrentModification exception in timer thread

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#561]
```
Got the following stack trace during startup or shortly after (no projects 
opened yet), while the system was under heavy paging load:

Exception in thread "Timer-2" java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:793)
    at java.util.HashMap$KeyIterator.next(HashMap.java:828)
    at edu.mit.simile.butterfly.ButterflyScriptWatcher.run(Butterfly.java:1099)
    at java.util.TimerThread.mainLoop(Timer.java:512)
    at java.util.TimerThread.run(Timer.java:462)

```

Original issue reported on code.google.com by `tfmorris` on 29 Apr 2012 at 5:36

**Comment by GoogleCodeExporter** [comment]
```
This appears to be due to a bug in the Simile project's ButterflyScriptWatcher 
class which doesn't synchronize access to a HashMap.

I've filed this bug http://code.google.com/p/simile-butterfly/issues/detail?id=8
```

Original comment by `tfmorris` on 18 Sep 2012 at 6:32
