### ISSUE TITLE
Export fails when previous export file exists - Google Chrome

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#585]
```
What steps will reproduce the problem?
1. Export a project using templating
2. Attempt to the project export again
3.

What is the expected output? What do you see instead?

I'd expect the browser to save the file as "projectname (1).txt"; or else 
prompt for a filename (+1 to the Save As... RFE from me)

What version of Google Refine are you using?
Google Refine 2.5 [r2407]

What operating system and browser are you using?
Fedora 16 32-bit; Google Chrome Version 20.0.1132.34 beta

Is this problem specific to the type of browser you're using or it happens
in all the browsers you tried?

It happens in Chrome. I tried with Firefox 13.0, and there I was prompted with 
a "Save As" dialog.


Please provide any additional information below.

Here's the server error message:

HTTP ERROR 500

Problem accessing /command/core/export-rows/EAP-6-Concepts.txt. Reason:

    INTERNAL_SERVER_ERROR
Caused by:

java.lang.UnsupportedOperationException
    at com.google.refine.commands.Command.doGet(Command.java:86)
    at com.google.refine.RefineServlet.service(RefineServlet.java:170)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
```

Original issue reported on code.google.com by `sitap...@worldsankirtan.net` on 21 Jun 2012 at 3:32

**Comment by GoogleCodeExporter** [comment]
```
When I try this in Chrome on Windows, I just get new file with "(1)" added to 
the filename as I'd expect.  I'll see if I can reproduce it on Linux.
```

Original comment by `tfmorris` on 18 Sep 2012 at 8:24
