### ISSUE TITLE
Patch: Update .classpath to export guava lib. Remove deprecated google-collect jar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#608]
```
Patch .classpath with attached patch file.
Remove extensions/gdata/module/MOD-INF/lib/google-collect-1.0-rc1.jar

Motivation: The guava lib completely replaces the deprecated google-collect lib.
```

Original issue reported on code.google.com by `s...@google.com` on 11 Sep 2012 at 7:42

Attachments:
- [patch](https://storage.googleapis.com/google-code-attachments/google-refine/issue-608/comment-0/patch)

**Comment by GoogleCodeExporter** [comment]
Original comment by `tfmorris` on 11 Sep 2012 at 10:50
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the patch!  Applied in r2545.
```

Original comment by `tfmorris` on 11 Sep 2012 at 11:06
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Can you also remove the file 
extensions/gdata/module/MOD-INF/lib/google-collect-1.0-rc1.jar since it is no 
longer needed.
```

Original comment by `s...@google.com` on 12 Sep 2012 at 6:48

**Comment by GoogleCodeExporter** [comment]
```
Good point.  It's gone now.
```

Original comment by `tfmorris` on 13 Sep 2012 at 6:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `tfmorris` on 18 Sep 2012 at 3:05
- Added labels: **Milestone-2.6**

**Comment by GoogleCodeExporter** [comment]
```
Hi, I'm getting this error while trying to import from googledocs:

java.lang.NoSuchMethodError: 
com.google.common.collect.ImmutableSet.of([Ljava/lang/Object;)Lcom/google/common
/collect/ImmutableSet;
    at com.google.gdata.wireformats.AltFormat$Builder.setAcceptableTypes(AltFormat.java:399)
    at com.google.gdata.wireformats.AltFormat$Builder.setAcceptableXmlTypes(AltFormat.java:387)
    at com.google.gdata.wireformats.AltFormat.<clinit>(AltFormat.java:49)
    at com.google.gdata.client.Service.<clinit>(Service.java:558)
    at com.google.refine.extension.gdata.GDataExtension.getDocsService(GDataExtension.java:97)
    at com.google.refine.extension.gdata.GDataImportingController.doListDocuments(GDataImportingController.java:127)

I'm launching from within Eclipse and Windows, I'm synced with the current 
version (2569), from what I see it seems gdata-core-1.0 is still calling the 
old library. Is it possible that the jar in the SVN is not up to date or am I 
missing something in the setup?

```

Original comment by `runuppat...@gmail.com` on 23 Sep 2012 at 9:37

**Comment by GoogleCodeExporter** [comment]
```
This can be fixed by updating the following gdata client libs from the latest 
version at 
http://gdata-java-client.googlecode.com/files/gdata-src.java-1.47.1.zip

M       extensions/gdata/module/MOD-INF/lib/gdata-core-1.0.jar
M       extensions/gdata/module/MOD-INF/lib/gdata-spreadsheet-3.0.jar
M       extensions/gdata/module/MOD-INF/lib/gdata-docs-3.0.jar
M       extensions/gdata/module/MOD-INF/lib/gdata-base-1.0.jar
M       extensions/gdata/module/MOD-INF/lib/gdata-spreadsheet-meta-3.0.jar
M       extensions/gdata/module/MOD-INF/lib/gdata-docs-meta-3.0.jar
M       extensions/gdata/module/MOD-INF/lib/gdata-client-1.0.jar
M       extensions/gdata/module/MOD-INF/lib/gdata-media-1.0.jar
M       extensions/gdata/module/MOD-INF/lib/gdata-client-meta-1.0.jar

```

Original comment by `s...@google.com` on 23 Sep 2012 at 10:42
