### ISSUE TITLE
ClassNotFoundException - could not find 'main' class on initial build

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Illablu/google-refine#7]
```
1.download/update source (r683)
2.using Cygwin 1.7 & JDK 6 update 20
3.# ./gridworks

Starting Gridworks at 'http://127.0.0.1:3333/'

Exception in thread "main" java.lang.NoClassDefFoundError:
com/metaweb/gridworks/Gridworks
Caused by: java.lang.ClassNotFoundException: 
com.metaweb.gridworks.Gridworks
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: com.metaweb.gridworks.Gridworks.  Program 
will exit.

```

Original issue reported on code.google.com by `iainsproat` on 10 May 2010 at 9:14

**Comment by GoogleCodeExporter** [comment]
```
I think it's an issue with the JAVA_HOME environmental variable in Cygwin.  I 
compiled 
the java using Eclipse and it runs fine. (after I remembered to add the -
Dbuild.dir=build -Ddist.dir=dist environmental variables when running in 
Eclipse)
```

Original comment by `iainsproat` on 10 May 2010 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
Resolved: My machine required a hard reboot in order for JAVA_HOME to be picked 
up by 
Cygwin.  Added a comment to the [http://code.google.com/p/freebase-
gridworks/wiki/DevelopersGuide developers guide] to help others.
```

Original comment by `iainsproat` on 10 May 2010 at 11:53

**Comment by GoogleCodeExporter** [comment]
Original comment by `stefano.mazzocchi@gmail.com` on 10 May 2010 at 3:55
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `iainsproat` on 11 May 2010 at 7:15
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
Original comment by `iainsproat` on 11 May 2010 at 7:17
- Added labels: **Type-Task**
- Removed labels: **Type-Defect**
